name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      region:
        description: "Região(us-west-1=dev, us-east-1=stage, sa-east-1=prod)"
        required: true
        type: choice
        options: [ "us-west-1", "us-east-1", "sa-east-1" ]
        default: "us-west-1"

env:
  AWS_REGION: ${{ inputs.region }}

jobs:
  build:    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: develop
            env: dev
            url: https://dev.example.com
          - branch: stage
            env: stage
            url: https://stage.example.com
          - branch: main
            env: prod
            url: https://example.com
    if: ${{ github.ref_name == matrix.branch }}
    environment:
      name: ${{ matrix.env }}
      url: ${{ matrix.url }}
    steps:          
      - name: Exibir variáveis específicas
        run: |
          echo "Branch: $GITHUB_REF"
          echo "Commit: $GITHUB_SHA"
          echo "Região AWS: $AWS_REGION"
          
      - name: Checkout
        uses: actions/checkout@v4

      # Exemplo genérico de build (ajuste conforme sua stack)
      - name: Build
        run: |
          echo "Build da $APP_NAME na branch $GITHUB_REF_NAME"
          # npm ci && npm run build
          # mv build/ artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.sha }}
          path: |
            artifact/**
            !**/*.log
