name: CI

on:
  push:
    branches: [main, develop, stage]
  pull_request:
    branches: [main, develop, stage]

  workflow_dispatch:
    inputs:
      region:
        description: "Região(us-west-1=dev, us-east-1=stage, sa-east-1=prod)"
        required: true
        type: choice
        options: [ "us-west-1", "us-east-1", "sa-east-1" ]
        default: "us-west-1"

env:
  AWS_REGION: ${{ inputs.region }}
  URL: "https://www.test.com"

jobs:
  deploy_dev:
    name: Deploy DEV
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'develop' }}
    environment: dev
    steps:
      - name: Exibir variáveis específicas
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: $GITHUB_REF"
          echo "Commit: $GITHUB_SHA"
          echo "Region env: $AWS_REGION"
          echo "Region var: ${{ vars.AWS_REGION }}"
          echo "API_KEY secrets: ${{ secrets.API_KEY }}"
          echo "URL: ${{ env.URL }}"


  deploy_stage:
    name: Deploy STAGE
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'stage' }}
    environment: stage
    steps:
      - name: Exibir variáveis específicas
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: $GITHUB_REF"
          echo "Commit: $GITHUB_SHA"
          echo "Region env: $AWS_REGION"
          echo "Region var: ${{ vars.AWS_REGION }}"
          echo "API_KEY secrets: ${{ secrets.API_KEY }}"
          echo "URL: ${{ env.URL }}"

  deploy_prod:
    name: Deploy PROD
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    environment: prod
    steps:
      - name: Exibir variáveis específicas
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: $GITHUB_REF"
          echo "Commit: $GITHUB_SHA"
          echo "Region env: $AWS_REGION"
          echo "Region var: ${{ vars.AWS_REGION }}"
          echo "API_KEY secrets: ${{ secrets.API_KEY }}"
          echo "URL: ${{ env.URL }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run a external script
        run: |
          chmod +x .github/scripts/custom.sh
          .github/scripts/custom.sh
          shell: bash
