name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      region:
        description: "Região(us-west-1=dev, us-east-1=stage, sa-east-1=prod)"
        required: true
        type: choice
        options: [ "us-west-1", "us-east-1", "sa-east-1" ]
        default: "us-west-1"

env:
  AWS_REGION: ${{ inputs.region }}

jobs:
  build:    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [ dev, stage, prod ]
    environment: ${{ matrix.env }}        
    steps:      
      - uses: actions/checkout@v4
      
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Exibir variáveis específicas
        run: |
          echo "Branch: $GITHUB_REF"
          echo "Commit: $GITHUB_SHA"
          echo "Região AWS: $AWS_REGION"
